#!/bin/bash

# Show command before executing
set -x

# We need to disable selinux for now, XXX
/usr/sbin/setenforce 0

# Get all the deps in
yum -y install \
  docker \
  make \
  git 
service docker start

# deploy to github pages
echo 'CICO: Deploying to github pages'
git fetch origin gh-pages
git checkout -b gh-pages origin/gh-pages

echo "This is true real funky awesome amazing wonka magic" > magic.html

# Update new repo with generated code
#git config user.name "ci.centos.org"
#git config user.email "almighty-public@redhat.com"
git add --ignore-removal --all .

#TODO add more context to msg
git commit -m "Generated by ci.centos.org" 

